classDiagram

    class aabqwer_1-a_dswqer1
    class aabqwer_1-a_dswqer1
    class aabqwer_1-a_dswqer1

    class aabqwer_1-a_dswqer
    aabqwer_1-a_dswqer1 --|> ClassB
    Person o-- Car
BankAccount : String owner
Order --> Invoice

